Feature: option to reverse slot cycle order
mmaulwurff/gearbox pull request #31
Opened 2022-07-11 18:56 UTC by Carrascado

When you press a slot key multiple times, the menu has to cycle the selection between all the available weapons in that slot.

- In this PR I introduce an option to reverse the order in which this cycling is done.
- The easiest mode to test it is with the blocks mode, but it works in all modes.
- Besides, the current order is considered now as "reversed", since I think the new order is more natural, but of course I leave to the reviewer's opinion whether to keep it this way. **In summary, top-to-bottom is "normal", and bottom-to-top is reverse.**
- I think this PR adds the option requested here: https://github.com/mmaulwurff/gearbox/issues/25, but not only for blocks, but for all selection configurations.

2022-07-12 13:25 UTC, mmaulwurff commented
As far as I understand, this PR solves only input part of #25 while leaving display unchanged. This PR has its uses, of course, just I wouldn't close #25 right away after this is merged.

2022-07-12 13:52 UTC, mmaulwurff requested changes

2022-07-12 14:43 UTC, Carrascado commented on zscript/gearbox/weapon_menu.zs
> +    if (mOptions.isSlotCycleOrderReversed()) {
That's a nice idea! I have refactored it and made sure it works by testing it again.

2022-07-12 15:18 UTC, merged

2022-07-13 13:48 UTC, mmaulwurff reviewed
+

2022-07-13 13:48 UTC, mmaulwurff reviewed
+